# Generated by Django 3.0.7 on 2020-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200622_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указывает сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='указывает сумму в долларах', verbose_name='Сборы В США'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указывает сумму в долларах', verbose_name='Сборы в мире'),
        ),
    ]
